name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linuxCpu]

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: cat README.md
        
      - run: echo ${{ github.ref }}
      
      - run: printenv
      
      - run: echo ${{ secrets.MY_SECRET }}
      
      - run: cat $GITHUB_EVENT_PATH

  build-win:
    runs-on: [self-hosted, windowsGpu]

    steps:
      - uses: actions/checkout@v2
        
      - run: echo ${{ github.ref }}
      
      - run: $env:PATH
        shell: powershell
      
      - run: echo ${{ secrets.MY_SECRET }}
      
      - run: cat $GITHUB_EVENT_PATH
